# Generated by Django 3.1.3 on 2020-12-16 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20201205_0023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='mail',
            field=models.EmailField(db_index=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='username',
            field=models.CharField(max_length=30),
        ),
    ]
